config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'welcome#show'

  get '/how-it-works', to: 'welcome#show'

  resources :coaches, only: [:create, :new, :edit]
  resources :practices, only: [:index]

  resources :coaches do
    get 'my_practices', to: 'coaches#my_practices'
    resources :practices
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  helper_method :date_calculator

  def date_calculator(day)
    @date = day.strftime("%A")
  end

  def get_days(event_recurrences)
    days = []
    event_recurrences.each do |i|
      days.push i.on
    end
    days
  end

  def index

  end

  def show
    @practices = Practice.all
    @current_user = current_user
    check_for_coach
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<section class="hero is-medium">
  <% if !current_user %>
    <div class="hero-head">
      <%= link_to "Join Now", new_coach_path, class:  "is-pulled-right button is-danger is-large"%>
    </div>
  <% end %>

  <div class="hero-body">
    <div class="container has-text-centered">

      <h1 class="main-welcome title is-1">
        <span class="coach-title">Coach</span>
        <span class="swap-title">Swap</span>
      </h1>
      <h2 class="tagline title is-3">
        Connecting the softball community one swap at a time
      </h2>

        <div class="block">
          <% if current_user %>
            <%= link_to "My Practice Schedule", "/coaches/#{session[:coach_id]}/practices", class: "button is-success is-medium" %>
          <% else %>
            <%= link_to "Login", login_path, class: "button is-danger is-medium"%>
          <% end %>
        </div>
        <a class="button is-dark is-medium">How it works</a>


    </div>
  </div>
</section>


  <div class="tile is-ancestor">
    <div class="tile is-4 is-parent">
      <div class="grow has-text-centered tile is-child box">
        <%= link_to new_coach_path do %>
        <p class="title">Step One</p>
        <p>Make a profile</p>
        <% end %>
      </div>
    </div>
    <div class="tile is-4 is-parent">
      <div class="grow tile is-child box">
        <p class="title">Step Two</p>
        <p>List your practice schedule for coaches in your area to watch</p>
      </div>
    </div>
    <div class="tile is-4 is-parent">
      <div class="grow tile is-child box">
        <p class="title">Step Three</p>
        <p>Find practices in your area to watch. Every swap earns you points!</p>
      </div>
    </div>
  </div>