config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'welcome#show'

  get '/how-it-works', to: 'welcome#show'

  resources :coaches, only: [:create, :new, :edit]
  resources :practices, only: [:index]

  resources :coaches do
    get 'my_practices', to: 'coaches#my_practices'
    resources :practices
  end

end

app/models/coach.rb
class Coach < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :practices
  belongs_to :user

  validates :name, :team, :age_group, :state, :email, :phone, :user_id, presence: :true
  validates_processing_of :avatar
  validate :avatar_size_validation

private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

  def self.authenticate_with_credentials(email, password)
    email = email.strip.downcase
    coach = Coach.find_by(email: email)
    if coach && coach.authenticate(password)
      coach
    else
      nil
    end
  end

  # User Avatar Validation

  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end

end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController

  def show
    @coach = Coach.find(params[:id])
    @practices = @coach.practices.where("date >= ?", Date.today).order(:date)
    @my_practices = Practice.where("guest_coach_id = ? AND date >= ?", @coach.id, Date.today).order(:date)
    if @my_practices.class == Practice
      @my_practices = [@my_practices]
    end
  end

  def new
    @coach = Coach.new
  end

  def create
    @coach = Coach.new(coach_params)
    @coach.user_id = current_user.id
    @coach.email = current_user.email
    if @coach.save
      flash[:notice] = "Great job on creating a profile! Next step is to join another team's practice or host a practice so other coaches can join."
      redirect_to "/coaches/#{@coach.id}/practices"
    elsif !@coach.valid?
      flash[:notice] = "All fields are required. We strive for a transparent platform for all coaches!"
      render :new
    end
  end

  def edit
    @coach = current_coach
  end

  def update
    coach = current_coach
    coach.update! update_coach_params
    redirect_to "/coaches/#{coach.id}"
  end


  private
  def coach_params
    params.require(:coach).permit(
      :avatar,
      :name,
      :team,
      :age_group,
      :state,
      :phone
    )
  end

  def update_coach_params
    params.require(:coach).permit(
      :avatar,
      :name,
      :team,
      :age_group,
      :state,
      :phone
    )
  end

end

app/helpers/coach_helper.rb
module CoachHelper
end

app/views/coaches/edit.html.erb
<div class="columns">
  <div class="column is-one-third"></div>
  <div class="column is-one-third">
    <h1 class="title is-2">Edit My Profile</h1>
    </br>
    <%= form_for @coach do |f| %>

      <%= f.file_field(:avatar) %>
      <p class="control has-icon">
        <%= f.text_field :name, :class => "input is-medium", :type => "text", :placeholder => "Name" %>
        <i class="fa fa-user" aria-hidden="true"></i>
      </p>
      <p class="control has-icon">
        <%= f.text_field :team, :class => "input is-medium", :type => "text", :placeholder => "Team Name" %>
        <i class="fa fa-users" aria-hidden="true"></i>
      </p>
      <p class="control">
        <span class="select is-medium">
          <%= f.select(:age_group, ["18U", "16U", "14U", "12U"]) %>
        </span>
      </p>
      <p class="control">
        <span class="select is-medium">
          <%= f.select(:state, ["Colorado"]) %>
        </span>
      </p>

      <p class="control has-icon">
        <%= f.text_field :phone, :class => "input is-medium", :type => "text", :placeholder => "555-555-5555" %>
        <i class="fa fa-users" aria-hidden="true"></i>
      </p>
      <%= f.submit("Submit", :class => "button is-success is-medium") %>
    <% end %>
  </div>
  <div class="column is-one-third"></div>
</div>

app/views/coaches/new.html.erb
<div class="columns">
  <div class="column is-one-third"></div>
  <div class="column is-one-third">
    <h1 class="title is-2">Create a Profile</h1>
    </br>
    <%= form_for @coach do |f| %>

      <span style="font-size: .75em">Profile Picture</span>
      </br>
      <%= f.file_field :avatar %>
      <p class="control has-icon">
        <%= f.text_field :name, :class => "input is-medium", :type => "text", :placeholder => "Name" %>
        <i class="fa fa-user" aria-hidden="true"></i>
      </p>
      <p class="control has-icon">
        <%= f.text_field :team, :class => "input is-medium", :type => "text", :placeholder => "Team Name" %>
        <i class="fa fa-users" aria-hidden="true"></i>
      </p>
      <p class="control">
        <span class="select is-medium">
          <%= f.select(:age_group, ["18U", "16U", "14U", "12U"]) %>
        </span>
      </p>
      <p class="control">
        <span class="select is-medium">
          <%= f.select(:state, ["Colorado"]) %>
        </span>
      </p>

      <p class="control has-icon">
        <%= f.text_field :phone, :class => "input is-medium", :type => "text", :placeholder => "555-555-5555" %>
        <i class="fa fa-users" aria-hidden="true"></i>
      </p>
      <%= f.submit("Create Profile", :class => "button is-success is-medium") %>
    <% end %>
  </div>
  <div class="column is-one-third"></div>
</div>

app/views/coaches/show.html.erb
<div class="columns">
  <div class="column is-2"></div>
  <div class="column is-4">
    <h1 class="title is-2">Profile Page <span class="edit-profile"><%=	link_to "Edit Profile", edit_coach_path, method: :get %></span></h1>

    <p class="subtitle is-4"><%= @coach.name %> - <%=	@coach.team %></p>
    <figure class="image is-128x128">
      <%= image_tag(@coach.avatar.thumb.url) if @coach.avatar_url %>
    </figure>
  </div>
</div>

<div class="columns">
  <div class="column is-2"></div>
  <div class="column is-4">
    <h2 class="subtitle is-4">My Practices</h2>
    <ul>
      <% @practices.each do |practice| %>
        <li class="my_practices">
          <%= practice.time.strftime("%l:%M %P") %>
          <%= practice.street %>
          <%= practice.city %>
          <%= practice.date.strftime("%m/%d/%Y") %>
          <br/>
          <span class="delete_practice"><%= link_to("Delete", "/coaches/#{params[:id]}/practices/#{practice.id}", method: :delete) %></span>
          <%= link_to("Edit", "/coaches/#{params[:id]}/practices/#{practice.id}/edit", method: :get) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="column is-1"></div>
  <div class="column is-4">
    <h2 class="subtitle is-4">Practices I'm attending</h2>
    <ul>
      <% if @my_practices %>
        <% @my_practices.each do |practice| %>
          <% host_coach = Coach.find(practice.coach_id) %>
          <li>
            <%= practice.time.strftime("%l:%M %P") %> <%= practice.team_name %> <br/>
            <%= practice.street %> <%= practice.city %> <%= practice.date.strftime("%m/%d/%Y") %> <br/>
            <span class="contact_coach">Contact Coach <%= host_coach.name %>: <%= host_coach.email %></span>
            <%=	form_tag(coach_practice_path(id: practice.id, coach_id: current_user.id, cancel_rsvp: "cancelled"), {class: "cancel_rsvp", method: :put}) do %>
              <%= submit_tag "Cancel RSVP", class: "cancel_rsvp" %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="column is-1"></div>
</div>